### ISSUE TITLE
service detail directory/yaml file structure discussion

### ISSUE THREAD

**Issue by jpetto** [mozmeao/status.mozmar.org#22]
I'm working on a PR to add a service detail view to the app, meaning it's about time to plan out a directory and file structure for service level alerts.

To keep things simple, we could start with file names that match the service id listed in `status.yml` - `alerts/dms-078f7f5a2f.yaml`, `alerts/nr-13687919.yaml`, `alerts/synthetics-ac74913d-4bb5-4ed5-8585-89065027764f.yaml`, etc. We could iterate on this (create a directory per service id?) to handle storing historical alerts.

In terms of service yaml file structure, how about this as a template/starting point:

``` yaml
alerts:
  yyyy-mm-dd-hh-mm-ss-ms:
    graph: {URL to iframe-able graph}
    description: {text}
    link: {URL}
    severity: {enum? (high|medium|low)}
    resolved: {bool}
    notes:
      yyyy-mm-dd-hh-mm-ss:
        note: {text}
```

Thoughts? I can create some dummy data in this format to get local dev going.

**Comment by glogiotatidis** [comment]
Is `yyyy-mm-dd-hh-mm-ss-ms` the timestamp of the moment we logged the event or the timestamp of the moment the event started? The two should only have a couple of minutes distance and it shouldn't matter too much but the `ss-ms` accuracy got my eye. 

I think that a list is more appropriate for the alerts and notes, sorted by descending datetime of alert or note. For example:

```
alerts:
 - yyyy-mm-dd-hh-mm-ss-ms:
    graph: {URL to iframe-able graph}
    description: {text}
 - yyyy-mm-dd-hh-mm-ss-ms-1:
    graph: {URL to iframe-able graph}
    description: {text}
```

**Comment by jpetto** [comment]
I was thinking the timestamp would correspond to the moment the alert occurred. That's probably better for potential historical/reporting means? I wouldn't be opposed to adding another data field for the timestamp of when the alert was logged though. More details are better, right?. The `ss-ms` data was just an assumption - should be fine if we don't have that degree of specificity.

The alerts and notes should definitely be lists - apologies for leaving them out of the original comment.

``` yaml
alerts:
  - yyyy-mm-dd-hh-mm-ss-ms:
    graph: {URL to iframe-able graph}
    description: {text}
    link: {URL}
    severity: {enum? (high|medium|low)}
    resolved: {bool}
    notes:
      - yyyy-mm-dd-hh-mm-ss:
        note: {text}
```
